### ISSUE TITLE
Highlight Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#100]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.1
**Description** - Highlight Issue

![scrnli_23_01_2023_17-55-37](https://user-images.githubusercontent.com/105413021/214039345-873e02b1-d2ca-438d-ad24-c716d3ac77f6.png)

**Comment by Ananya-Cedcoss** [comment]
![Screenshot from 2023-01-24 13-36-58](https://user-images.githubusercontent.com/79438168/214240827-d1181fe8-1eb2-493c-92c4-d808bc009188.png)

not getting this error

**Comment by ashish-wps** [comment]
It's working on developer system.
