### ISSUE TITLE
phpcs Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#101]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.1
**Description** - phpcs Issue

[PHPcs.docx](https://github.com/wpswings/wallet-system-for-woocommerce/files/10479690/PHPcs.docx)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fix
