### ISSUE TITLE
Total amount Issue when user add partial payment

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#102]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - Total amount Issue when user add partial payment
**Steps** - 
1. Add any product. ( Product amount is greater than wallet amount )
2. Go to the Checkout
3. Pay some amount from wallet.
4. Check Total amount.

![scrnli_22_02_2023_15-00-03](https://user-images.githubusercontent.com/105413021/220580052-7f0b24aa-ba0a-4b67-a049-2a900bb705ff.png)

**Comment by Ananya-Cedcoss** [comment]
![Screenshot from 2023-02-23 19-36-31](https://user-images.githubusercontent.com/79438168/220930613-67403667-3cf3-43d5-b1bf-888b7683847f.png)
same settings i have applied but did not get the issue

**Comment by ashish-wps** [comment]
Fixed

**Comment by ashish-wps** [comment]
![image](https://user-images.githubusercontent.com/105413021/225192615-667a51d1-469a-4606-8d6a-3554310098f4.png)

**Comment by ashish-wps** [comment]
According to the developer, This issue is not from our plugin
