### ISSUE TITLE
 User can pay more than wallet amount ( Wallet Partial Payment Method issue )

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#103]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - User can pay more than wallet amount ( Wallet Partial Payment Method issue )
**Steps** -
1. Add some product in cart.
2. Enable the Wallet Partial Payment Method.
3. Pay some amount with partial payment ( **Condition** -  if your total amount is 70 and your wallet amount 50. Than pay 30 because then your total is less than your wallet amount )
4. Select the wallet payment method.
5. Place the order.
6. Verify the result.

https://user-images.githubusercontent.com/105413021/220582905-16fca5e1-08bc-41bc-8514-6584bd612fe5.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
https://user-images.githubusercontent.com/105413021/225189258-df1ef4e0-2f3e-43cf-81e0-d676d7b4cbc8.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
![screencapture-localhost-10008-checkout-2023-03-15-18_48_44](https://user-images.githubusercontent.com/105413021/225320619-ef316576-b55e-400e-8fce-384667536827.png)
