### ISSUE TITLE
Calendar is not working properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#105]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - Calendar is not working properly

![scrnli_22_02_2023_15-52-11](https://user-images.githubusercontent.com/105413021/220595864-639b93c2-9180-465f-bf1f-e1b7e1d0557c.png)

**Comment by Ananya-Cedcoss** [comment]
removed dates from search setting

**Comment by ashish-wps** [comment]
**Note** - Calendar is not working pro plugin.
**Enhancement** - Please add calendar ( Time Slot ) in Transactions Export file. So User download only the required Transactions detail.

**Comment by Sukirti-CEDCOSS** [comment]
Verified
