### ISSUE TITLE
When user enable Gateway Restriction Message but didn't select any gateway

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#106]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - When user enable Gateway Restriction Message but didn't select any gateway

![scrnli_22_02_2023_16-39-50](https://user-images.githubusercontent.com/105413021/220604296-00613b98-89b2-4784-875c-e21be9bf4da4.png)

![image](https://user-images.githubusercontent.com/105413021/220604330-9e5aa6f5-ba3e-4e40-8bd6-7ac673b04fcb.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
