### ISSUE TITLE
Currency Switcher issue on Order received page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#107]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - Currency Switcher issue on **Order received** page

![scrnli_24_02_2023_18-25-37](https://user-images.githubusercontent.com/105413021/221184077-94abe579-7565-4f39-b7dc-06b8e56e9f3f.png)

https://drive.google.com/drive/folders/19I9jF4t5d4hiuRzNN5X19Uba12yilkF8?usp=sharing

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Okay
