### ISSUE TITLE
QA issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#108]
**WooCommerce Version** - 7.4.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.2
**Description** - WooCommerce Version is not updated ( in both plugin )

![image](https://user-images.githubusercontent.com/105413021/221192906-bb0564d9-a706-4f13-9e6a-86830fbae391.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
