### ISSUE TITLE
Transactions are not showing

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#109]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - Transactions are not showing

![scrnli_14_03_2023_13-52-34](https://user-images.githubusercontent.com/105413021/224987684-eaed3fdc-f253-45df-9339-429a5838021b.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
