### ISSUE TITLE
Highlight Missing

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#111]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - Highlight Missing

![image](https://user-images.githubusercontent.com/105413021/224999225-01ad1b31-fd02-4af5-9cb6-3393dc90eb3b.png)

**Comment by Ananya-Cedcoss** [comment]
![Screenshot from 2023-03-15 10-18-00](https://user-images.githubusercontent.com/79438168/225242238-365ac2aa-ccc4-4e9f-9a15-2c9d25d53523.png)

**Comment by ashish-wps** [comment]
According to developer, It's not an issue.
