### ISSUE TITLE
Please show Wallet Withdrawal Request

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#112]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - Please show Wallet Withdrawal Request

https://user-images.githubusercontent.com/105413021/225001233-3cc5b269-8852-4675-b0ba-96bdfcef9c13.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
