### ISSUE TITLE
Wallet Withdrawal Request Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#113]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - Wallet Withdrawal Request Issue

https://user-images.githubusercontent.com/105413021/225006328-dcaa6ebf-b2ee-467f-8ca6-eb1c0b5ad162.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed
