### ISSUE TITLE
Show Warning when activate the plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#115]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - Show Warning when activate the plugin

![image](https://user-images.githubusercontent.com/105413021/225335038-a599aaf0-c83a-438d-bf67-85489e6a98c7.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
