### ISSUE TITLE
It's give caskback on tax included amount

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#116]
**WooCommerce Version** - 7.4.1
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.4
**Description** - It's give caskback on tax included amount

![image](https://user-images.githubusercontent.com/105413021/225573080-bca18b63-2fdd-48e7-8813-ef01f37ef4fd.png)

**Comment by Ananya-Cedcoss** [comment]
we will check the possibility of implementing this in next version
