### ISSUE TITLE
PHPcs Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#118]
[wallet-system-for-woocommerce.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/11598619/wallet-system-for-woocommerce.zip)
[PHPcs.xml.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/11598622/PHPcs.xml.zip)

**Comment by Ananya-Cedcoss** [comment]
Fixed and WOOCS and WCMP are third party variable unable to fix

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
