### ISSUE TITLE
PHPcs 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#119]
File:
[wallet-system-for-woocommerce.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/11956091/wallet-system-for-woocommerce.zip)

**Comment by Ananya-Cedcoss** [comment]
rest of the issues are not able to resolve due to third party and  {  issue can not be fixed as it is not issue

**Comment by Sukirti-CEDCOSS** [comment]
verified
