### ISSUE TITLE
Show Error when admin update wallet manually

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#122]
WooCommerce Version - 8.0.0
Wordpress Version - 6.3
Plugin Version - 2.4.0
Description - Show Error when admin update wallet manually

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/43f32360-3f46-4cf2-9c47-4775667d4188)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
