### ISSUE TITLE
Notification Error when admin deduct more than exist value

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#123]
WooCommerce Version - 8.0.0
Wordpress Version - 6.3
Plugin Version - 2.4.0
Description - Notification Error when admin deduct more than exist value

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/ef68ffec-e537-4f36-ae5e-4aad854ba3b1)

https://nimb.ws/0e6jz8

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
