### ISSUE TITLE
Add Balance request showing in both order section [order and Wallet Recharge order]

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#124]
**WooCommerce Version** - 8.0.0
**Wordpress Version** - 6.3
**Plugin Version** - 2.4.0
**Description** - Add Balance request showing in both order section [order and Wallet Recharge order]
**Note** - HPOS Issue

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/01882873-ad7a-4990-b51c-f99fab538358)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/c76af6dc-7392-4274-9012-e129d384def1)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
