### ISSUE TITLE
Issue in Partial payment when admin deduct amount while placing order

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#125]
**WooCommerce Version** - 8.0.0
**Wordpress Version** - 6.3
**Plugin Version** - 2.4.0
**Description** - Issue in Partial payment when admin deduct amount while placing order

https://nimb.ws/OXcSBg

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
