### ISSUE TITLE
Add Balance request show with tax in Wallet Recharge Orders

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#126]
WooCommerce Version - 8.0.0
Wordpress Version - 6.3
Plugin Version - 2.4.0
Description - Add Balance request show with tax in Wallet Recharge Orders

https://nimb.ws/fUWnCH

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a5e718f8-8f3f-441a-98cd-a5ef57cf91b3)

**Comment by Ananya-Cedcoss** [comment]
This is not an issue working correct in demo

**Comment by ashish-wps** [comment]
Okay
