### ISSUE TITLE
Generated Tax is not correct when user apply wallet amount

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#127]
**WooCommerce Version** - 8.0.0
**Wordpress Version** - 6.3
**Plugin Version** - 2.4.0
**Description** - Generated Tax is not correct when user apply wallet amount

**Wallet** : 
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/22dd0830-fbe1-4c1a-a85f-42927ec41dea)

**Coupon** : 
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a6979e47-5746-4aa6-9c61-2028f93cc937)

**Comment by Ananya-Cedcoss** [comment]
![Screenshot from 2023-09-12 15-52-42](https://github.com/wpswings/wallet-system-for-woocommerce/assets/79438168/1bbf68f8-876d-4408-bf50-bf4fdc369ab3)
![Screenshot from 2023-09-12 15-53-01](https://github.com/wpswings/wallet-system-for-woocommerce/assets/79438168/8d118856-12f5-4d44-8d3e-5c57acf4b11f)


fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
