### ISSUE TITLE
Show Error in Wallet Action Page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#128]
**WooCommerce Version** - 8.0.0
**Wordpress Version** - 6.3
**Plugin Version** - 2.4.0
**Description** - Show Error in Wallet Action Page

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/3dc03017-197a-43b9-9553-47873f5433df)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
