### ISSUE TITLE
Design issue on Calendar in the Transaction tab

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#129]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
Design issue on Calendar in the Transaction tab
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/582f8f68-29e0-42d8-8c35-2013473ef028)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
