### ISSUE TITLE
The "PRO" tag is overlapping on the heading

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#130]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The "PRO" tag is overlapping on the heading

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/4fd07569-4bfa-41a6-9af6-386e594b9faa)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
