### ISSUE TITLE
The Search is placed in distance inappropriately

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#131]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The Search is placed in distance inappropriately
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/35d9f36a-8dd0-47ba-81fa-5c81d8d0e818)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
