### ISSUE TITLE
The "PRO" tag should be added to setting

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#132]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The "PRO" tag should be added to setting
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/f21df54f-1ccb-458e-94e3-7316e81628f7)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
