### ISSUE TITLE
The wallet payment method option does not appear when we enabled a negative wallet balance setting

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#133]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The wallet payment method option does not appear when we are enabling a negative wallet setting
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/598765ff-3f50-4bd2-8a9c-452efc6db394)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
