### ISSUE TITLE
PHPcs Issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#134]
[PHPcs.xml.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/12575813/PHPcs.xml.zip)
[wallet-system-for-woocommerce.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/12575817/wallet-system-for-woocommerce.zip)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
