### ISSUE TITLE
Fatal error when Oder is made by partial wallet payment

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#136]
WooCommerce Version - 8.0.3
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
Fatal error when Oder is made by partial wallet payment
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/f3caadbe-3a4e-4bd7-8742-c5edba1a9fd8)
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/d901578e-94df-412b-af96-6706e168ac33)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
