### ISSUE TITLE
The amount should not be less than 0 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#137]
WooCommerce Version - 8.1.0
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The amount should not be less than 0 

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/b78b6f9c-6f96-42f2-9406-b8da6ea82015)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
