### ISSUE TITLE
The Wallet recharge is not visible on the orders page

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#138]
WooCommerce Version - 8.1.0
WordPress Version - 6.3.1
Plugin Version - 2.5.0
Description -
The Wallet recharge is not visible on the orders page
 
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/dffdb578-06f5-4882-9c7c-46c88a172f07)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
