### ISSUE TITLE
The pro tag should be there on the delete action

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#140]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
The pro tag should be there on the delete action
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/f0894fe3-3a2d-455f-b282-0202481635af)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
