### ISSUE TITLE
There is an unnecessary gap in the header section that does not look nice for design purposes

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#141]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
There is an unnecessary gap in the header section that does not look nice for design purposes
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/42211691-c2b0-42da-8920-a4136c7a70d4)

**Comment by Ananya-Cedcoss** [comment]
fixed
