### ISSUE TITLE
As we are changing Rows per page the page number on the right side should change accordingly

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#142]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
As we are changing Rows per page the page number on the right side should change accordingly

https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/ccc54910-1e67-4b48-a4af-a4107f1a39f7

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
