### ISSUE TITLE
The ability to modify table data should also be given as per the date

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#143]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
The ability to modify table data should also be given as per the date
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/aa634396-6475-4f76-84eb-bcfe65df8e01)

**Comment by Ananya-Cedcoss** [comment]
date filter is already available and due to date format it is not able to sort according to date

**Comment by Sukirti-CEDCOSS** [comment]
Verified
