### ISSUE TITLE
Add + and - sign on the amount as we are displaying on the frontend

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#146]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
Add + and - sign on the amount as we are displaying on the frontend
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/fb04e999-9f2e-44a2-88de-a9431ab0218e)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
