### ISSUE TITLE
Error is showing when we are debiting the amount from the user as an admin

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#147]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
Error is showing when we are debiting the amount from the user as an admin
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/1a5f1069-0b35-4ce7-a207-5816295750f9)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
