### ISSUE TITLE
When we are debating the amount from the user as an admin the wallet amount changes to the amount we are debating

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#148]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
When we are debating the amount from the user as an admin, the wallet amount changes to the amount we are debating

https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/8649f3bb-5ad4-4c1e-babd-f58fbf522a56

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
