### ISSUE TITLE
Warning on the wallet transaction page

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#150]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
Warning on the wallet transaction page
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/c6c8965d-f564-4704-952f-8a79e220b0bf)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
