### ISSUE TITLE
Design issue on wallet user table Action column

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#151]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
Design issue on wallet user table Action column. 
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/8b7ccff3-899e-4c90-b4d7-3cbe63685c13)
The pro tag should be on the delete column after we click the view button.
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/548fc589-4818-4e31-be7e-fa2984d96571)

**Comment by Ananya-Cedcoss** [comment]
Fixed
