### ISSUE TITLE
The user is not receiving mail on credit or debit amount by Admin

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#152]
Status - New
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description -
The user is not receiving mail on credit or debit amount by Admin
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/85384857/82f8606a-92fd-4cc5-9fef-87ddb2aee395)

**Comment by Ananya-Cedcoss** [comment]
check it once on demo

**Comment by ashish-wps** [comment]
Still Exist

**Comment by Ananya-Cedcoss** [comment]
Email is working fine please check

**Comment by ashish-wps** [comment]
Issue is still exist at my end

**Comment by Ananya-Cedcoss** [comment]
resolved

**Comment by ashish-wps** [comment]
Fixed
