### ISSUE TITLE
Please remove unnecessary "Cash On Delivery" option 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#154]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Please remove unnecessary "Cash On Delivery" option 

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/8f7d8d8f-ee7a-4293-be67-0ccb350de7bc)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
