### ISSUE TITLE
User able to enter negative value in Wallet Negative Balance and  Wallet interest Amount

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#155]
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description - User able to enter negative value in Wallet Negative Balance and  Wallet interest Amount

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/ccaeb4a8-5eb8-4702-8c0d-a862d93cd944)

[scrnli_27_10_2023_16-02-55.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/fed26829-4018-44d6-835c-1aff7ea2d7a9)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/f7331234-6650-4e9a-ac66-8700033712a5)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
