### ISSUE TITLE
Debit amount from user's wallet feature is not working properly with negative balance user

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#156]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Debit amount from user's wallet feature is not working properly with negative balance user

[scrnli_27_10_2023_16-30-43.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a4e428f1-4073-4c4a-8b2e-3a5dfe47f47b)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
