### ISSUE TITLE
User able to enter apposite Amount Restriction

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#158]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - User able to enter apposite Amount Restriction

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/77096ac6-9243-46c1-90ba-a162246575fb)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
