### ISSUE TITLE
user able to use more than negative balance limit

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#160]
Woo Commerce Version - 8.2.0
WordPress Version - 6.3.2
Plugin Version - 2.5.3
Description - user able to use more than negative balance limit

[scrnli_31_10_2023_11-22-03.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/32894af4-1424-4d5c-9b88-e9ba98b7c74d)

**Comment by Ananya-Cedcoss** [comment]
fixed
