### ISSUE TITLE
Page stuck on refresh when user enter negative value while debit the amount

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#161]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Page stuck on refresh when user enter negative value while debit the amount

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/4b9b2e7b-d5d6-45e0-b3a1-2328e36c0cab)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
