### ISSUE TITLE
Show warning when user deduct amount from wallet option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#162]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Show warning when user deduct amount from wallet option

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/be528946-2c6b-432d-bb71-6e1393687d74)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
