### ISSUE TITLE
When checkout page refreshing than recharge amount change into 0

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#163]
**Woo Commerce Version** - 8.3.1
**WordPress Version** - 6.4.1
**Plugin Version** - 2.5.5
**Description** - When checkout page refreshing than recharge amount change into 0

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/844554fc-de0e-4715-8cc7-e99ee940a584)

[scrnli_04_12_2023_13-14-53.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/6f8e37dd-ebd4-438f-81a5-472ac16d9f01)

**Comment by Ananya-Cedcoss** [comment]
not getting this issue

**Comment by ashish-wps** [comment]
I am providing the video and screenshot of the issue.

[scrnli_06_12_2023_12-33-02.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/5a3412d3-f913-4e9a-8f54-b7d59f005afb)

![Screenshot from 2023-12-06 12-33-15](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a02cabec-0499-438a-abeb-954fec811f4e)

**Comment by ashish-wps** [comment]
[scrnli_12_12_2023_13-17-09.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/8b95eaec-c2bf-4281-98a2-ac450840dad6)

**Comment by ashish-wps** [comment]
Fixed
