### ISSUE TITLE
 Fatal Error

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#164]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** Fatal Error

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/e7f55a01-704f-4d1b-81a6-a3ca835324b6)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
