### ISSUE TITLE
Unnecessary text shown on "Order received" page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#165]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** Unnecessary text shown on "Order received" page

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/1ccfbfbb-b6ed-47c7-a63f-179630839279)

**Comment by Ananya-Cedcoss** [comment]
did not getting this issue
