### ISSUE TITLE
Wallet Payment and Partial Payment both shown on checkout page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#166]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** Wallet Payment and Partial Payment both shown on checkout page

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/062f78b1-4f40-4e74-8da7-04abd8eae4a7)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Partial Payment Option "Total Wallet Amount" feature is not working

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/84ab3c58-a0bd-4860-8b27-78e27b5fabe8)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/268b4d0e-68f6-417c-ac11-3e182a3cafc0)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/b3cb15ff-6806-415c-b572-55a9eeb678a4)

**Comment by ashish-wps** [comment]
Fixed

**Comment by ashish-wps** [comment]
![Uploading image.png…]()

**Comment by ashish-wps** [comment]
Fixed
