### ISSUE TITLE
checkout page For Wallet Rechargeable Product feature is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#171]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** checkout page For Wallet Rechargeable Product feature is not working

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/9c667d5b-a28e-4540-9c73-d61371f59f04)

**Comment by Ananya-Cedcoss** [comment]
currently it works with woocommerce_checkout shortcode in future will implement in block checkout

**Comment by ashish-wps** [comment]
Okay
