### ISSUE TITLE
User should get cashback on subtotal

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#174]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.5
Description -** User should get cashback on subtotal

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/b70609ea-7268-4823-bb94-ea709fc41f7d)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
