### ISSUE TITLE
Fatal error when user comment on post

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#175]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.5
Description -** Fatal error when user comment on post

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a0af0a2c-c039-4bf1-ad9a-0147a9e018a2)

[scrnli_15_12_2023_17-35-09.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/b730b023-4126-4237-b195-7859fca552a7)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
