### ISSUE TITLE
Wallet Payment and Cash on delivery option shown on wallet recharge 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#176]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -** Wallet Payment and Cash on delivery option shown on wallet recharge 

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/48aada28-eaf7-4940-957e-3707aa8b346a)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/4d300ecd-caf0-47ae-ab94-c3e6d710f1eb)

**Comment by Ananya-Cedcoss** [comment]
issue is resolved

**Comment by ashish-wps** [comment]
Fixed

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/9d675ff6-16cc-4ae5-ab47-753db46c771e)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/55a3ef85-1028-4a17-821e-84a7fbc43d27)
