### ISSUE TITLE
 Fatal Error

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#177]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -** Fatal Error

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/2270bb2b-dec2-470e-aa1c-c714ab0d634b)

**Comment by Ananya-Cedcoss** [comment]
issue is resolved

**Comment by ashish-wps** [comment]
Resolved
