### ISSUE TITLE
Wallet amount is not deduct when user deduct any amount before place order

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#178]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -** Wallet amount is not deduct when user deduct any amount before place order

[scrnli_15_01_2024_14-30-50.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/eea58485-56f8-4365-8e6d-62ecc7a8cea3)

**Comment by Ananya-Cedcoss** [comment]
notice will come after apply wallet  but due to page refresh get removed

**Comment by ashish-wps** [comment]
okay
