### ISSUE TITLE
Partial Payment Option > Total wallet amount feature is not working properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#179]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -**  Partial Payment Option > Total wallet amount feature is not working properly

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/9fb4c237-b148-4b10-b343-edd53fb9b0b9)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/dd90ef0b-951d-4f5a-b9a3-b26864dddf86)

**Comment by Ananya-Cedcoss** [comment]
fixed
