### ISSUE TITLE
Partial Payment > Manual Wallet Amount issue when wallet is more than Total but less than subtotal

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#180]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -** Partial Payment > Manual Wallet Amount issue when wallet is more than Total but less than subtotal

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/679efeb7-fdd2-4645-adf0-724b3fa8b323)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/37d993f5-f095-4669-bea5-0734ab63257d)

**Comment by Ananya-Cedcoss** [comment]
dependent on woocommerce will fix it when woocommerce get updated

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Wallet payment option is not showing when amount in equal to cart total

[scrnli_14_02_2024_13-56-15.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/e988371f-2d0b-4248-bc3f-3c520bb7abbf)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/89b6786f-2c66-413f-970a-1af0322197f2)


Tax should visible when admin enter full amount

**Comment by ashish-wps** [comment]
Fixed
