### ISSUE TITLE
Transaction is not showing when user have negative balance ( Admin Add Order from admin panel )

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#181]
Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description - Transaction is not showing when user have negative balance ( Admin Add Order from admin panel )

[scrnli_29_01_2024_16-00-25.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/1b54144d-5a47-4743-85fd-bbe3c8efd9f0)

**Comment by Ananya-Cedcoss** [comment]
fixed
