### ISSUE TITLE
Recharge Product Tax Free feature is not working when tax are inclusive 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#182]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.5.6
Description -** Recharge Product Tax Free feature is not working when tax are inclusive 

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/774b1c74-edfc-4554-8d0c-295cb4c2246d)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/588b76fc-1405-48e4-8226-cba852c38bb2)

**Comment by Ananya-Cedcoss** [comment]
will fix in next update

**Comment by ashish-wps** [comment]
Fixed
