### ISSUE TITLE
Partial Payment issue when user enter full amount manually

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#183]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.5.6
Description -** Partial Payment issue when user enter full amount manually

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/357b1ae7-d24b-4d43-a22d-2e711d4a69f4)

**Comment by Ananya-Cedcoss** [comment]
This issue comes when decimal value is in very minute for example 94.9994587  so it that case it is creating issue will check in future

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

**Comment by ashish-wps** [comment]
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/c59d8b1b-474d-4de4-b893-093f48eb2aa7)

**Comment by Ananya-Cedcoss** [comment]
did not get the issue to resolve it

**Comment by ashish-wps** [comment]
Fixed
