### ISSUE TITLE
User should not able to enter percentage more than 100

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#184]
**Woo Commerce Version - 8.4.0
WordPress Version - 6.4.2
Plugin Version - 2.5.6
Description -** User should not able to enter percentage more than 100

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/62e1357e-e358-470e-91c4-4e02aa3888c6)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
