### ISSUE TITLE
Partial Payment Method (Total wallet amount) feature is not working properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#187]
**Woo Commerce Version - 8.8.3
WordPress Version - 6.5.2
Plugin Version - 2.5.12
Description -** Partial Payment Method (Total wallet amount) feature is not working properly

[scrnli_02_05_2024_12-34-02.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/7c659024-63bf-48fe-9348-ebb039934945)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
