### ISSUE TITLE
User should able to leave blank Min cart amount and Maxi Wallet Cashback 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#188]
**Woo Commerce Version - 8.8.3
WordPress Version - 6.5.2
Plugin Version - 2.5.12
Description -** User should able to leave blank Min cart amount and Maxi Wallet Cashback 

[scrnli_02_05_2024_13-03-04.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/63855e01-317f-49c5-8a05-6b8e03399983)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

**Comment by ashish-wps** [comment]
fatal error when changing the wallet product order status

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/c006fda9-ad46-4e79-8d74-48993ec22cd3)

**Comment by ashish-wps** [comment]
Fixed
