### ISSUE TITLE
Move Cashback for Wallet Recharge setting in PRO plugin and add Pro tag

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#189]
**Woo Commerce Version - 8.8.3
WordPress Version - 6.5.2
Plugin Version - 2.5.12
Description -** Move Cashback for Wallet Recharge setting in PRO plugin and add Pro tag

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/940680eb-2173-4bbd-9cde-9fa234045abf)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
fixed
