### ISSUE TITLE
Wallet cashback is not working properly with Tax for all product

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#191]
**Woo Commerce Version - 8.8.3
WordPress Version - 6.5.2
Plugin Version - 2.5.12
Description -** Wallet cashback is not working properly with Tax for all product

[scrnli_02_05_2024_13-25-26.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/00938aa2-4d45-42ce-bd99-6dc2eecea1c1)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/8bbe0a96-ae2f-437e-8a78-2d96421d8c87)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
