### ISSUE TITLE
Decimal value ( 0.02 ) should debit from wallet

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#192]
**Woo Commerce Version - 8.8.3
WordPress Version - 6.5.2
Plugin Version - 2.5.12
Description -** Decimal value ( 0.02 ) should debit from wallet
**Note -** Wallet decimal amount should show in report section

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/398693f2-6eae-4d5b-be2a-2d6eb1b5a104)

**Comment by Ananya-Cedcoss** [comment]
will fix it next update

**Comment by Shivamddeveloper** [comment]
issue fixed now

**Comment by ashish-wps** [comment]
Fixed
