### ISSUE TITLE
set notification default color according to theme and provided the color pallete  for that

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#197]
**Woo Commerce Version - 9.1.4
WordPress Version - 6.6.1
Plugin Version - 2.5.16
Description -** 
1. Please set notification default color according to theme and provided the color pallete  for that.
2. And remove warning sign and replace with tick sign

![image](https://github.com/user-attachments/assets/d6713b23-d186-4e1d-b0b2-7f55fc5b04fd)

![image](https://github.com/user-attachments/assets/664b870a-72db-4452-96ea-169f6becd933)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
