### ISSUE TITLE
wps_wsfw_credit_user_wallet_balance calls intval when it shouldn't

### ISSUE THREAD

**Issue by petermorlion** [wpswings/wallet-system-for-woocommerce#198]
In the `wps_wsfw_credit_user_wallet_balance` function, the amount I pass in is modified to an integer. I believe this is a bug, because it should be possible to credit $2.40 for example. This would now be modified to $2.

The call to intval should probably be modified to floatval?

**Comment by ashish-wps** [comment]
thanks for pointing this issue, we have checked it in our plugin code and you are suggesting right things , so we have modify the change in our plugin and it will also release in coming update of this month
