### ISSUE TITLE
Can't able to enable the Wallet Action functionality 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#199]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 2.6.0
Description -** Can't able to enable the Wallet Action functionality 

[scrnli_jyJ0GbxtxX917e.webm](https://github.com/user-attachments/assets/3620011c-56b2-4db2-a338-a252c670a156)

**Comment by Shivamddeveloper** [comment]
issue solved

**Comment by ashish-wps** [comment]
Fixed
