### ISSUE TITLE
Win Wheel Rule is not working for wallet plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#200]
**Woo Commerce Version - 9.3.3
WordPress Version - 6.6.2
Plugin Version - 2.6.0
Description -** Win Wheel Rule is not working for wallet plugin

[scrnli_Dhsb0qEe25CRqm.webm](https://github.com/user-attachments/assets/f3bbe9a1-06d1-47ab-a15b-b6f55987b1f3)

**Comment by Shivamddeveloper** [comment]
i have again cross check this feature i found it is working properly and i think you are facing this issue because you are not testing with update par plugin for this feature.

https://www.awesomescreenshot.com/video/32932304?key=1900aa2836ee674599235cf9949b503d

**Comment by ashish-wps** [comment]
Fixed
