### ISSUE TITLE
How to define a ratio of the value of the coins?

### ISSUE THREAD

**Issue by Anatal** [wpswings/wallet-system-for-woocommerce#201]
Every 100 coins are worth 16.67 dollar.
How can this be defined?

**Comment by WP-Swings** [comment]
Hello,

Thank you for using our plugin!

Regarding your inquiry, you can easily set up the redemption rate according to your preferences in our Points plugin. To do this, please follow these steps:

Navigate to General Settings >> Redemption Settings. Here, you'll be able to configure the rate to suit your needs.

For this configuration please check our other plugin for points functionality :https://wpswings.com/product/points-and-rewards-for-woocommerce-plugin/ 

Regards,

**Comment by Anatal** [comment]
It doesn't save me a number with a decimal point, just a whole number. I've attached a screenshot.
![image](https://github.com/user-attachments/assets/329a698b-05e0-4e35-bcbb-30ef1db510fa)

**Comment by WP-Swings** [comment]
Hello ,

Thank you for your reply!

In reference to your query , our plugin currently do not support a decimal number system so you need to enter values in whole number.

Regards
