### ISSUE TITLE
QA/PHPcs issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#39]
Files:
[PHPcs-ORG.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7963351/PHPcs-ORG.zip)
[wallet-system-for-woocommerce.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7963352/wallet-system-for-woocommerce.zip)

[PHPcs-PRO.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7963355/PHPcs-PRO.zip)
[woocommerce-wallet-system.zip](https://github.com/Makewebbetter/wallet-system-for-woocommerce/files/7963356/woocommerce-wallet-system.zip)

**Comment by Ananya-Cedcoss** [comment]
issues which will effect the plugin working is not fixed.
phpcs issues are fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
