### ISSUE TITLE
The user details are not displayed in the wallet table

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#40]
WordPress: 5.9.1
WooCommerce: 6.2.1
Description:
The user details are not displayed in the wallet table
![image](https://user-images.githubusercontent.com/85384857/155836934-c482d468-08f7-4b8d-92be-21ff15770c63.png)

**Comment by navneet-cedcoss** [comment]
This issues comes from folder name, because wallet pro plugin name and slug should be changed, so when a new name updated on git issues sholud be resolved.

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
