### ISSUE TITLE
Payment option - Manual wallet amount seems not to be working 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#41]
WordPress: 5.9.1
WooCommerce: 6.2.1
Description:
Payment option - Manual wallet amount seems not to be working 
we should be able to manually enter the amount in  this setting.
![image](https://user-images.githubusercontent.com/85384857/155838321-dd7f6604-69d3-4245-9f1a-ba79c46ff8c7.png)
![image](https://user-images.githubusercontent.com/85384857/155843978-7da2dea3-d164-499c-8997-17055b8bdda7.png)

**Comment by navneet-cedcoss** [comment]
Partial payment option should only show when wallet amount is less than order total amount.
This is the default functionality.

**Comment by Sukirti-CEDCOSS** [comment]
not an issue
