### ISSUE TITLE
Define the functionality with the correct explanation 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#42]
WordPress: 5.9.2
WooCommerce: 6.3.1 
Description:
Define the functionality with the correct explanation 
![image](https://user-images.githubusercontent.com/85384857/161717377-f5fd2dba-666d-45f2-a36d-3cb836def7de.png)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
