### ISSUE TITLE
Use similar case-type wherever it is suitable

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#43]
WordPress: 5.9.2
WooCommerce: 6.3.1
Description:
Use similar case-type wherever it is suitable
![image](https://user-images.githubusercontent.com/85384857/161719063-fac9df43-eff9-47e2-bf4d-2815cac9cb85.png)
![image](https://user-images.githubusercontent.com/85384857/161719242-6f97695b-11c2-4e64-afe5-d674ec33b0a9.png)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
