### ISSUE TITLE
Create restrictions on the input value

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#44]
WordPress: 5.9.2
WooCommerce: 6.3.1
Description:
Create restrictions on the input value, and make them mandatory. User should not be able to save the settings with empty data
![image](https://user-images.githubusercontent.com/85384857/161760720-bee76a13-ec76-4447-bda4-52b002b09809.png)
![image](https://user-images.githubusercontent.com/85384857/161760942-68ccd737-87a9-4350-82e7-35177a6eeaf5.png)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
