### ISSUE TITLE
Cashback setting on a category wise option

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#45]
WordPress: 5.9.2
WooCommerce: 6.3.1
Description:
setting-->Category Wise cashback
If this is the setting, please specify it on a dashboard so that user can choose accordingly
The Cashback percentage increases with the products in the cart
![image](https://user-images.githubusercontent.com/85384857/161765951-8149e436-9d13-4320-aa69-1e26e358b987.png)
While in the fixed method the Cashback amount is fixed 
![image](https://user-images.githubusercontent.com/85384857/161766334-fc670b0b-dede-4f98-92b8-948845df59ad.png)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
