### ISSUE TITLE
specify that "Maximum Wallet Cashback Amount" with not be effective on a category wise cashback

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#46]
WordPress: 5.9.2
WooCommerce: 6.3.1
Description:
Please specify that  "Maximum Wallet Cashback Amount" with not be effective on a category wise cashback, so that the user will not be confused
![image](https://user-images.githubusercontent.com/85384857/161767345-44a4179f-ee0f-479e-ab3a-ebf03f7e5d2d.png)

![image](https://user-images.githubusercontent.com/85384857/161767273-40685393-1558-4060-9bfb-e1cce3fd44ee.png)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
