### ISSUE TITLE
Add a Cashback option in the order list so that users can check later on 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#47]
WordPress: 5.9.2
WooCommerce: 6.3.1
Description:
Add a Cashback option in the order list so that users can check later on 
![image](https://user-images.githubusercontent.com/85384857/161767792-58e57abe-f4f2-4c6f-b780-e605cb5a8380.png)

**Comment by Ananya-Cedcoss** [comment]
This is not a valid issues as we can not mention cashback on placing order as It can be cancelled or refunded.
We will notify user via a mail about cashback

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
