### ISSUE TITLE
QA/PHPcs

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#49]
Files:

[wallet-system-for-woocommerce.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/8440884/wallet-system-for-woocommerce.zip)
[wallet-system-for-woocommerce-phpcs.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/8440891/wallet-system-for-woocommerce-phpcs.zip)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
