### ISSUE TITLE
If the admin deleted the comment after approval and the user already got the credit amount. Will the user is again eligible for the amount credit for comment.

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#52]
WordPress: 5.9.3
WooCommerce: 6.4.1
Description:
If the admin deleted the comment after approval and the user already got the credit amount. Will the user is again eligible for the amount credit for comment.
![image](https://user-images.githubusercontent.com/85384857/165925647-7be41180-5041-441c-b49e-3bca14032cfb.png)
.....
![image](https://user-images.githubusercontent.com/85384857/165925862-f3e6e17c-f254-4025-83d6-de1b1561318f.png)
.......
![image](https://user-images.githubusercontent.com/85384857/165925753-ba70e041-d250-41c4-9061-f50dc9ad86c1.png)
.......
![image](https://user-images.githubusercontent.com/85384857/165926210-10260daf-76f8-4f7e-b1a2-c071b8d6e9d7.png)

**Comment by navneet-cedcoss** [comment]
If admin delete comment of any user, then again user will get comment points.

**Comment by Sukirti-CEDCOSS** [comment]
verified
