### ISSUE TITLE
A new user on commenting is getting a credit amount as many times as the user is commenting in spite of the limit in setting

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#53]
WordPress: 5.9.3
WooCommerce: 6.4.1
Description:
A new user on commenting is getting a credit amount as many times as the user is commenting in spite of the limit in setting
![image](https://user-images.githubusercontent.com/85384857/165937970-528ea122-643d-4470-8f1e-2244147aee51.png)
![Wallet-System-for-WooCommerce-Pro-Demo-WP-Swings](https://user-images.githubusercontent.com/85384857/165938173-666b0a68-10d5-488a-90b0-30121b7b96b3.png)
![image](https://user-images.githubusercontent.com/85384857/165938427-9c07c7b1-3a5c-4b23-b248-1df8e603d0c9.png)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
