### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#54]
WordPress: 5.9.3
WooCommerce: 6.4.1
Description:
The search box design is different 
![image](https://user-images.githubusercontent.com/85384857/166649771-29ca33d9-1c16-4aaa-8ab1-a1aff302d82a.png)
....
....
![image](https://user-images.githubusercontent.com/85384857/166649969-f0fb205f-6b8e-4af3-add5-fe74c6c2e6ab.png)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
