### ISSUE TITLE
QA/PHPcs Issues 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#57]
QA Issues:
1. Update:
WC Requires at least: 5.1.0
WP tested up to: 6.0.0

File:
[PHPcs.zip](https://github.com/wpswings/wallet-system-for-woocommerce/files/8764033/PHPcs.zip)

**Comment by Ananya-Cedcoss** [comment]
only one i.e- $WCMp  issue is left which can not be fixed because code is coming from other plugin during compatibility
others are fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
