### ISSUE TITLE
Put the proper description for the Partial payment option Dropbox 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#58]
WordPress: 6.0.0
WooCommerce: 6.5.1
Description:
Put the proper description for the Partial payment option Dropbox 
![image](https://user-images.githubusercontent.com/85384857/172114075-4db4808f-f6f6-4980-93e9-444c64d4e4eb.png)

**Comment by Shivamddeveloper** [comment]
issue Resolved 
![Wallet-System-‹-lastest-wallet-site-—-WordPress (8)](https://user-images.githubusercontent.com/87006389/172176250-199e26cd-e17d-4ebe-82a7-b1866ecc7f95.png)

**Comment by Sukirti-CEDCOSS** [comment]
verified
