### ISSUE TITLE
In the Wallet tab, the transaction details input box has unnecessary arrows

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#60]
WordPress: 6.0.1
Woocommerce: 6.7.0
Description: 
In the Wallet tab, the transaction details input box has unnecessary arrows
![image](https://user-images.githubusercontent.com/85384857/180695265-22410a74-c0d1-4474-ba32-1a9465fb8e63.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
