### ISSUE TITLE
The search section in the Wallet transaction tab is out of design

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#61]
WordPress: 6.0.1
Woocommerce: 6.7.0
Description:
The search section in the Wallet transaction tab is out of design
![image](https://user-images.githubusercontent.com/85384857/180695518-8ee00518-4370-4703-bf59-f675775002e5.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
