### ISSUE TITLE
On purchase of subscription product the amount paid via wallet is not showing in thank you page

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#63]
WordPress: 6.0.1
Woocommerce: 6.7.0
Description:
On purchase of subscription product, the amount paid via wallet is not showing on thank you page
![image](https://user-images.githubusercontent.com/85384857/180696184-a4a59b20-abbb-430f-b244-0fcfd7870f7c.png)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by Ananya-Cedcoss** [comment]
![Checkout-–-subscription-site](https://user-images.githubusercontent.com/79438168/180937106-c27fe12f-52e1-4adc-a81f-9bfb42998992.png)
![Checkout-–-subscription-site (1)](https://user-images.githubusercontent.com/79438168/180937121-8e1330b8-3935-4b5c-b5b4-ba66d2ab1df9.png)

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
