### ISSUE TITLE
Malware issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#64]
**Malware issue:**
ObfuscatedPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-orders-list.php
0x13ea:$concat_with_spaces: $orders = $wpdb->get_results( $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
0x13f4:$concat_with_spaces: $wpdb->get_results( $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
0x1408:$concat_with_spaces: $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
0x16df:$concat_with_spaces: $orders = $wpdb->get_results( $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
0x16e9:$concat_with_spaces: $wpdb->get_results( $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
0x16fd:$concat_with_spaces: $wpdb->prepare( 'SELECT DISTINCT ID FROM ' . $wpdb->prefix . 'posts INNER JOIN ' . $wpdb->postmeta . ' ON ' . $wpdb->prefix . 'posts.ID = ' . $wpdb->postmeta . 
DangerousPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-system-for-woocommerce-admin.php
0x93:$system: System
0xc0:$system: System
**PHP files:**
DangerousPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-system-for-woocommerce-admin.php
ObfuscatedPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-orders-list.php

**Comment by Ananya-Cedcoss** [comment]
Query Issue is fixed 
Ignore the system issue as it is coming from plugin text domain

**Comment by Sukirti-CEDCOSS** [comment]
fine for now
