### ISSUE TITLE
Showing Error after activate the plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#66]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Showing Error after activate the plugin
**Steps** - 
1. Download the plugin.
2. Activate the plugin.
3. Go to the General Setting.
4. Enable the plugin.
5. Verify the result.
![My account – Wallet](https://user-images.githubusercontent.com/105413021/189647772-7d8b4460-5b7e-4314-88b5-fa91e4b699cb.png)

**Comment by Shivamddeveloper** [comment]
issue resolved

**Comment by ashish-wps** [comment]
Fixed
