### ISSUE TITLE
Add Balance option is not working and flash a error notification

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#67]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Add Balance option is not working and flash a error notification
**Steps -**

1. Download the plugin.
2. Activate the plugin.
3. Go to the site > my account
4. Go to the Wallet option
5. Add balance in wallet.
6. Verify the result.]

https://user-images.githubusercontent.com/105413021/189837147-f90e644b-27b4-4885-8183-918fb41422bd.mp4

**Comment by Shivamddeveloper** [comment]
issue resolved

**Comment by ashish-wps** [comment]
Fixed

**Comment by ashish-wps** [comment]
Still not working...

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
