### ISSUE TITLE
Export pdf option is showing error notification

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#68]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Export pdf option is showing error notification
**Steps -**

1. Download the plugin.
2. Activate the plugin.
3. Go to the Wallet system plugin > Wallet Transactions page
4. Click on Export pdf option
5. Verify the result.

https://user-images.githubusercontent.com/105413021/189838141-bb520535-2a8b-46c7-a540-26a3812a6972.mp4

**Comment by Shivamddeveloper** [comment]
i have cross check this point again and it is working proerply so kindly check by your self on new or demo site

**Comment by ashish-wps** [comment]
I checked on Live demo and that functionality is still  not working.

https://user-images.githubusercontent.com/105413021/190080698-4dc9fc0f-8f80-4ce2-b431-ce723d1acdcb.mp4

**Comment by Ananya-Cedcoss** [comment]
It was due to missing of vendor folder but now its working

**Comment by ashish-wps** [comment]
Fixed
