### ISSUE TITLE
1st product is not getting removed from cart when enable the woocs plugin

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#69]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - 1st product is not getting removed from cart when enable the woocs plugin
**Steps** - 
1. Activate the woocs plugin.
2. Add some product in cart.
3. Try removing the first product.
4. Verify the result.

https://user-images.githubusercontent.com/105413021/190082080-b047c106-8d42-4387-9e89-38060713c553.mp4

**Comment by Ananya-Cedcoss** [comment]
It is issue from woocs plugin not from our plugin

**Comment by ashish-wps** [comment]
okk
