### ISSUE TITLE
 show a error on checkout page and cart page.

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#70]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** -  show a error on checkout page.
Steps -

1. Activate the woocs plugin.
2. Add some product in cart.
3. Try to place order.
4. Verify the result.

![Checkout – Wallet](https://user-images.githubusercontent.com/105413021/190106422-e59920f7-9f48-4d34-8846-ffacb85156e7.png)

![Cart – Wallet](https://user-images.githubusercontent.com/105413021/190106469-f5d47d02-e492-415b-a067-6d14df794873.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fix
