### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#71]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Design issue
**Steps -**

1. Activate the woocs plugin.
2. Go to the wallet system plugin option.
3. Go to the wallet action page.
4. Verify the result.
![Wallet System ‹ Wallet System for WooCommerce Pro Demo _ WP Swings — WordPress (1)](https://user-images.githubusercontent.com/105413021/190086742-5f7ec797-4dc6-4c1c-84b8-ff227beaa6a6.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
