### ISSUE TITLE
Malwae issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#72]
DangerousPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-system-for-woocommerce-admin.php
0x93:$system: System
0xc0:$system: System
0x1c8:$system: System
0x1f5:$system: System
0x255:$system: System
0x644:$system: system
0x6a9:$system: SYSTEM
0x6e7:$system: system
0x75c:$system: SYSTEM
0x80c:$system: SYSTEM
0x8c1:$system: SYSTEM
0x96d:$system: SYSTEM
0xa13:$system: SYSTEM
0xa4b:$system: system
0xae2:$system: SYSTEM
0xb75:$system: SYSTEM
0xc2b:$system: SYSTEM
0xc5e:$system: system
0xd2c:$system: SYSTEM
0xd6a:$system: system
0xddf:$system: SYSTEM
0xe8f:$system: SYSTEM
0xf44:$system: SYSTEM
0xff0:$system: SYSTEM
0x1087:$system: SYSTEM
0x1167:$system: system
0x1194:$system: SYSTEM
0x11cd:$system: system
0x132d:$system: system
0x13b6:$system: SYSTEM
0x13f4:$system: system
0x1472:$system: SYSTEM
0x1521:$system: SYSTEM
0x15d6:$system: SYSTEM
0x1685:$system: SYSTEM
0x16bb:$system: system
0x1893:$system: system
0x1940:$system: system
0x19a9:$system: system
0x1a09:$system: system
0x1a73:$system: system
0x1ae0:$system: system
0x1bc4:$system: SYSTEM
0x1c57:$system: SYSTEM
0x1c89:$system: system
0x1d5e:$system: SYSTEM
0x1d94:$system: system
0x23e3:$system: system
0x246b:$system: system
0x266d:$system: system
0x28cd:$system: System
0x29fd:$system: SYSTEM
0x307d:$system: system
0x3216:$system: System
0x32fc:$system: System
0x330d:$system: system
0x3342:$system: system
0x337a:$system: system
0x3408:$system: System
0x3534:$system: SYSTEM
0x358c:$system: System
0x3614:$system: SYSTEM
0x364d:$system: system
0x368f:$system: System
0x3842:$system: system
0x38e7:$system: system
0x39da:$system: system
0x3a15:$system: system
0x3a7b:$system: system
0x3b12:$system: system
0x3c1d:$system: system
0x3c58:$system: system
0x3cbf:$system: system
0x3d64:$system: system
0x3e77:$system: system
0x3eb2:$system: system
0x3f38:$system: system
0x3fdd:$system: system
0x4118:$system: system
0x4153:$system: system
0x41c7:$system: system
0x4299:$system: system
0x43d5:$system: system
0x442a:$system: system
0x4585:$system: system
0x4754:$system: system
0x47e2:$system: system
0x492c:$system: system
0x4967:$system: system
0x49d6:$system: system
0x4a7b:$system: system
0x4bf7:$system: system
0x4e43:$system: system
0x4ee8:$system: system
0x5047:$system: system
0x5082:$system: system
0x50ec:$system: system
0x5199:$system: system
0x532c:$system: system
0x53bb:$system: system
0x545f:$system: system
0x5632:$system: system
0x5892:$system: system
0x5937:$system: system
0x5a90:$system: system
0x5acb:$system: system
0x5b42:$system: system
0x5bfc:$system: system
0x5d74:$system: system
0x5e0e:$system: system
0x5ed4:$system: system
0x61ef:$system: system
0x629a:$system: system
0x63ea:$system: system
0x6425:$system: system
0x6491:$system: system
0x653b:$system: system
0x66bb:$system: system
0x6747:$system: system
0x67f2:$system: system
0x697b:$system: system
0x6a0b:$system: system
0x6aa0:$system: system
0x6c62:$system: system
0x6e00:$system: system
0x70db:$system: system
0x7236:$system: system
0x72db:$system: system
0x7404:$system: system
0x743f:$system: system
0x74ad:$system: system
0x756d:$system: system
0x76fa:$system: system
0x773f:$system: system
0x778a:$system: system
0x77d3:$system: system
0x7845:$system: system
0x7930:$system: system
0x7aa1:$system: system
0x7aed:$system: system
0x7b63:$system: system
0x7c27:$system: system
0x7d98:$system: system
0x7e1f:$system: system
0x7f8f:$system: system
0x7fd2:$system: system
0x804c:$system: system
0x80dd:$system: system
0x8205:$system: system
0x828f:$system: system
0x8308:$system: system
0x844d:$system: system
0x84e2:$system: system
0x855f:$system: system
0x86b4:$system: system
0x8838:$system: system
0x88b6:$system: System
0x93a8:$system: system
0x93ec:$system: System
0x97d8:$system: system
0xa09a:$system: system
0xa15f:$system: system
0xa250:$system: system
0xa28f:$system: System
0xaa3d:$system: system
0xab02:$system: system
0xae5b:$system: system
0xb00c:$system: system
0xb0cd:$system: system
0xb1a6:$system: system
0xb2bd:$system: system
0xb325:$system: system
0xb38b:$system: system
0xb431:$system: system
0xb7e0:$system: System
0xb946:$system: system
0xb9af:$system: system
0xbaf0:$system: system
0xbb4a:$system: system
0xbba5:$system: system
0xbd58:$system: system
0xbd9e:$system: system
0xbe70:$system: system
0xc0a9:$system: system
0xc2d1:$system: system
0xc333:$system: system
0xc662:$system: system
0xcaa7:$system: System
0xcdf2:$system: system
0xcfe1:$system: system
0xd027:$system: system
0xd079:$system: system
0xd100:$system: system
0xd1b3:$system: system
0xd35f:$system: system
0xd4d5:$system: system
0xdb7d:$system: system
0xdc09:$system: system
0xdcc3:$system: system
0xde61:$system: system
0xe169:$system: system
0xe458:$system: system
0xe49e:$system: system
0xe4ef:$system: system
0xe585:$system: system
0xe638:$system: system
0xe7d8:$system: system
0xe87a:$system: system
0xebb7:$system: system
0xec6e:$system: system
0xede3:$system: system
0xf124:$system: system
0xf1e1:$system: system
0xf325:$system: system
0xf39a:$system: system
0xf4d2:$system: system
0xf539:$system: system
0xf6dc:$system: system
0x105dd:$system: SYSTEM
0x106b1:$system: SYSTEM
0x10bb6:$system: system
0x10cbd:$system: system
0x10f63:$system: System
0x11379:$system: system
0x113bf:$system: system
0x1145f:$system: system
0x11515:$system: system
0x116d0:$system: system
0x1180b:$system: system
0x11995:$system: system
0x11a91:$system: system
0x11ce1:$system: system
0x11efb:$system: system
0x12100:$system: system
0x12156:$system: system
0x121b1:$system: system
0x12210:$system: system
0x1226f:$system: system
0x122d0:$system: system
0x1231e:$system: system
0x12382:$system: system
0x123dc:$system: system
0x12457:$system: system
0x12637:$system: system
0x12851:$system: system
0x12a44:$system: system
0x13528:$system: system
0x13585:$system: system
0x135ea:$system: system
0x13647:$system: system
0x13c3b:$system: System
0x14043:$system: system
0x14089:$system: system
0x14126:$system: system
0x141d6:$system: system
0x1437e:$system: system
0x14720:$system: system
0x148e4:$system: system
0x149a5:$system: system
0x14ad6:$system: system
0x14b7e:$system: system
0x14c74:$system: system
0x14cd2:$system: system
0x14d13:$system: system
0x14d7d:$system: system
0x14e08:$system: system
0x14efb:$system: system
0x14fee:$system: system
0x16021:$system: SYSTEM
0x16107:$system: SYSTEM
0x161f8:$system: SYSTEM
0x163fc:$system: system
0x1645a:$system: system
0x164b9:$system: system
0x1650f:$system: system
0x16561:$system: system
0x165c4:$system: system
0x16627:$system: system
0x1667c:$system: system
0x166d2:$system: system
0x1672a:$system: system
0x16785:$system: system
0x1680f:$system: system
0x18071:$system: system
0x18741:$system: System
0x18823:$system: system
0x1889f:$system: system
0x189e5:$system: system
0x18a64:$system: system
0x18dd8:$system: system
0x18e1e:$system: system
0x18e71:$system: system
0x18eed:$system: system
0x18fa6:$system: system
0x19145:$system: System
0x192c7:$system: system
0x19358:$system: system
0x19479:$system: system
0x194b4:$system: system
0x19551:$system: system
0x195c1:$system: system
0x1972a:$system: system
0x19774:$system: system
0x19834:$system: system
0x1990b:$system: system

path-

DangerousPhp /home/cedcoss/Desktop/wallet-system-for-woocommerce/admin/class-wallet-system-for-woocommerce-admin.php

**Comment by Ananya-Cedcoss** [comment]
It is included in slug therefore unable to resolve it.

**Comment by ashish-wps** [comment]
okk
