### ISSUE TITLE
phpcs issues

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#73]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - phpcs issues

[PHPcs.docx](https://github.com/wpswings/wallet-system-for-woocommerce/files/9565325/PHPcs.docx)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Shivamddeveloper** [comment]
some issue need to be ignore because it is comtability with woocs plugin due to which it is showing phpcs error we need to ignore this

**Comment by ashish-wps** [comment]
ok
