### ISSUE TITLE
Currency didn't convert after Wallet recharge

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#74]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Currency didn't convert after Wallet recharge
Steps -

1. Activate the woocs plugin.
2. Go to the site > My account > Wallet
3. Add balance to account
4. Verify the result.

https://user-images.githubusercontent.com/105413021/190134199-9b84b9ef-2b0a-4f84-9e93-4fa1efec0ad1.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fix
