### ISSUE TITLE
Error notification showing on order received page

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#75]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Add Balance option is not working and flash a error notification
**Steps -**

1. Download the plugin.
2. Activate the plugin.
3. Go to the site > my account
4. Go to the Wallet option
5. Add balance in wallet.
6. Verify the result.
![Checkout – Wallet (2)](https://user-images.githubusercontent.com/105413021/190331484-9ddd0b54-1b24-481d-af7d-5453cb0216b2.png)

**Comment by Shivamddeveloper** [comment]
issue fixed
