### ISSUE TITLE
Partial Payment Option is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#76]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Partial Payment Option is not working
**Prerequisite** - Your wallet amount is less than your cart amout
**Steps -**
1. Go to the shop page
2. Add some products
3. Enable the Partial Payment Option 
4.  Place the order.
5. Go to wallet.
6. Verify the result.

https://user-images.githubusercontent.com/105413021/190338891-60fae367-e821-4941-bfaf-698194ee3411.mp4

**Comment by Shivamddeveloper** [comment]
this is not issue this is enchantment so you can ignore this

**Comment by ashish-wps** [comment]
Fix
