### ISSUE TITLE
Language issue 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#78]
**WooCommerce Version** - 6.8.2
**Wordpress Version** - 6.0.2
**Plugin Version** - 2.2.8
**Description** - Language issue 
![Wallet System-Text ‹ Wallet — WordPress](https://user-images.githubusercontent.com/105413021/190377731-d44bbd50-da55-4b7a-b095-b3ea24a9c8d7.png)

**Comment by Shivamddeveloper** [comment]
issue fixed

**Comment by ashish-wps** [comment]
Fix
