### ISSUE TITLE
phpcs Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#80]
**WooCommerce Version** - 7.0.0
**Wordpress Version** - 6.0.3
**Plugin Version** - 2.2.9
**php version** - 8.0.0
**Description** - phpcs Issue

[PHPcs.docx](https://github.com/wpswings/wallet-system-for-woocommerce/files/9820353/PHPcs.docx)

**Comment by rishabhmwb** [comment]
some issues are fixed and some issues are left because they are the key words defined in third party plugin so we can not change them

**Comment by ashish-wps** [comment]
[PHPcs.docx](https://github.com/wpswings/wallet-system-for-woocommerce/files/9900672/PHPcs.docx)

Okay
