### ISSUE TITLE
Can't able to login

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#81]
**WooCommerce Version** - 7.0.0
**Wordpress Version** - 6.0.3
**Plugin Version** - 2.2.9
**php version** - 8.0.0
**Description** - Can't able to login

[My-account-–-Wallet (2).webm](https://user-images.githubusercontent.com/105413021/196697567-36865e61-df9a-4e4c-8627-f3c43f065357.webm)

**Comment by rishabhmwb** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
