### ISSUE TITLE
Design Issue in Avada Theme

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#82]
**WooCommerce Version** - 7.0.0
**Wordpress Version** - 6.0.3
**Plugin Version** - 2.2.9
**php version** - 8.0.0
**Description** - Design Issue in Avada Theme

![scrnli_19_10_2022_18-27-24](https://user-images.githubusercontent.com/105413021/196698055-b97f5093-7b11-4f0e-a607-688cbef95c4e.png)

**Comment by rishabhmwb** [comment]
if this issue is with this only theme then leave it we can handle it individually if any issue will come from client side

**Comment by ashish-wps** [comment]
Okay
