### ISSUE TITLE
On 0 balance debit the amount, It's showing on wallet transaction

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#84]
**WooCommerce Version** - 7.2.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.0
**Description** - On 0 balance debit the amount, It's showing on wallet transaction

https://user-images.githubusercontent.com/105413021/208019621-b3fcbff8-6d68-4e56-8e19-de1e263a4160.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
