### ISSUE TITLE
Debit more amount more than wallet

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#85]
**WooCommerce Version** - 7.2.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.0
**Description** - Debit more amount more than wallet

https://user-images.githubusercontent.com/105413021/208022256-24fd909d-5782-4153-8110-aa13f325382c.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
If the amount entered is more then actual amount then provide a notice on the pop-up, that enter less or equal amount
![image](https://user-images.githubusercontent.com/85384857/208813041-75040a61-9cbc-4059-9925-5814aa4fadae.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed


![scrnli_22_12_2022_13-11-23](https://user-images.githubusercontent.com/105413021/209082739-548ba7d1-6dcd-4fd2-a45a-3bfbe1add02d.png)
