### ISSUE TITLE
When User enter Transaction Detail than "unable to debit amount due to Insufficient Balance ie." is not visible

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#86]
**WooCommerce Version** - 7.2.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.0
**Description** - When User enter Transaction Detail than "unable to debit amount due to Insufficient Balance ie." is not visible

https://user-images.githubusercontent.com/105413021/208050798-f48c6db3-efa3-4eb7-a9eb-a6068648ea47.mp4

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
