### ISSUE TITLE
Wallet Cashback "Category Wise" option is not working properly

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#87]
**WooCommerce Version** - 7.2.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.0
**Description** - Wallet Cashback "Category Wise" option is not working properly

https://user-images.githubusercontent.com/105413021/208055720-73e83e27-4aab-4c0e-bb5f-dac407b28c4d.mp4

![scrnli_16_12_2022_12-12-06](https://user-images.githubusercontent.com/105413021/208055848-36927485-9e4d-40da-930b-2c7fc2117fb8.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
