### ISSUE TITLE
 Show error in Wallet Actions option

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#88]
**WooCommerce Version** - 7.2.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.0
**Description** - Show error in Wallet Actions option

![scrnli_19_12_2022_09-34-44](https://user-images.githubusercontent.com/105413021/208346404-5b78b572-f2d9-4682-b83b-b759fa189bc9.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
