### ISSUE TITLE
Payment should display in detail. Short code is appearing

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#89]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description -
Payment should display in detail. Shortcode is appearing
![image](https://user-images.githubusercontent.com/85384857/208657399-fd435789-f1c0-443a-a89e-eb924a614221.png)

**Comment by Ananya-Cedcoss** [comment]
this is the slug of wallet payment gateway which represt payment method and details are in details section

**Comment by ashish-wps** [comment]
Okay.. It's working fine according to developer.
