### ISSUE TITLE
Use correct description

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#90]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description - 
Use correct description
![image](https://user-images.githubusercontent.com/85384857/208811313-21d6dea0-6d18-4b1a-af22-38080fbc451f.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
