### ISSUE TITLE
The amount should not go in negative value or 0

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#91]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description -
The amount should not go in a negative value or 0
![image](https://user-images.githubusercontent.com/85384857/208814306-ff791555-ecea-497a-baf2-3f572f7ffadc.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed


![scrnli_22_12_2022_13-17-37](https://user-images.githubusercontent.com/105413021/209084112-2248c295-fe31-4942-956f-05f3777e6c19.png)
