### ISSUE TITLE
A warning occurred when emptied user's balance personally

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#92]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description -
A warning occurred when emptied user's balance personally
![image](https://user-images.githubusercontent.com/85384857/208815991-6f40fe4b-c06e-4a7e-82c5-a623dbd4f5c4.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
