### ISSUE TITLE
Transaction detail is not visible when debiting user balance personally

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#93]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description -
Transaction detail is not visible when debiting user balance personally
![image](https://user-images.githubusercontent.com/85384857/208816115-d32ae9ce-f22a-4113-95fc-711662d319c2.png)
![image](https://user-images.githubusercontent.com/85384857/208817830-661ed2a8-2a7f-4ea3-9df3-c81c58a6854a.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

![scrnli_22_12_2022_13-31-34](https://user-images.githubusercontent.com/105413021/209087959-53eade4b-7119-4383-b288-c624830335fa.png)
