### ISSUE TITLE
If we are paying partial amount via wallet there is not option to pay remaining amount by stripe 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#95]
WooCommerce Version - 7.2.1
WordPress Version - 6.1.1
Plugin Version - 2.3.0
Description -
If we are paying a partial amount via wallet there is not option to pay remaining amount by stripe 
![Checkout-–-Funnel](https://user-images.githubusercontent.com/85384857/208837139-8dd3ae69-a051-4226-9156-fe84c24387e9.png)
![Checkout-–-Funnel(1)](https://user-images.githubusercontent.com/85384857/208837342-6c63b60e-47b0-4689-8ff1-783422ebcd82.png)
refer:
https://wordpress.org/support/topic/error-when-total-wallet-amount-applied-is-more-than-the-net/

**Comment by Sukirti-CEDCOSS** [comment]
not an issue

**Comment by Ananya-Cedcoss** [comment]
not an issue it is due to woocommerce

**Comment by ashish-wps** [comment]
Okay
