### ISSUE TITLE
Refund to user wallet button is not working

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#96]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.1
**Description** - Refund to user wallet button is not working

![scrnli_23_01_2023_16-57-12](https://user-images.githubusercontent.com/105413021/214028979-5a3b66bb-2726-4f38-a361-b012b9b0d223.png)

**Comment by Ananya-Cedcoss** [comment]
it is working perfectly please check again i have checked it on new site
https://www.loom.com/share/0cc6fb65b124455a95060be0d830f650

**Comment by ashish-wps** [comment]
Okay
