### ISSUE TITLE
Content Issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#98]
**WooCommerce Version** - 7.3.0
**Wordpress Version** - 6.1.1
**Plugin Version** - 2.3.1
**Description** - Content Issue

![scrnli_23_01_2023_17-43-39](https://user-images.githubusercontent.com/105413021/214037182-a0932606-4f86-40a9-ad12-03334c53ffca.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fix
